@Ignore
Feature: Title of your feature
  I want to use this template for my feature file

  @Ignore
  Scenario: CBPCL-200 TC1 Accident Incident type, cause and subcauses will cause correct validation at end of step3
    When I add "<incidents added>" to the claim
    And I add "<parties added>" to the claim
    And I select "Next"
    Then I will see the validation errors "<validation errors>"
      | incident type | cause                                                | sub cause                                                                                                        | incidents added                      | parties added              | validation errors |
      | Accident      | Accident Involving Animal                            | Collided with animal - owner known                                                                               | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Animal                            | Collided with animal - owner unknown                                                                             | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Animal                            | Damage caused by vermin / birds                                                                                  | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Animal                            | Swerved to avoid an animal which ran into the road, collided with parked vehicle                                 | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Animal                            | Swerved to avoid an animal which ran into the road, collided with an oncoming vehicle                            | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Animal                            | Swerved to avoid an animal - vehicle left road                                                                   | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Accident Involving Cyclist                           | Struck cyclist crossing                                                                                          | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Accident Involving Cyclist                           | Lost control due to mechanical failure                                                                           | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Accident Involving Cyclist                           | Struck cyclist turning left                                                                                      | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Accident Involving Cyclist                           | Struck cyclist turning right                                                                                     | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Accident Involving Cyclist                           | Struck cyclist whilst passing                                                                                    | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian crossing from nearside from between parked vehicles                                            | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian on pedestrian crossing                                                                         | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian crossing road                                                                                  | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian/child whilst reversing                                                                         | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian on pelican crossing - lights in our favour                                                     | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Accident Involving Pedestrian                        | Struck pedestrian on pelican crossing - lights not in our favour                                                 | Insured Vehicle                      | Insured Driver, Pedestrian | no errors         |
      | Accident      | Car Door Open                                        | Third party opened car door into path of insured                                                                 | Insured Vehicle, Third Party Vehicle | Insured Driver             | no errors         |
      | Accident      | Car Door Open                                        | Insured opened car door into path of passing third party                                                         | Insured Vehicle, Third Party Vehicle | Insured Driver             | no errors         |
      | Accident      | Car Door Open                                        | Insured door already open when hit by third party                                                                | Insured Vehicle, Third Party Vehicle | Insured Driver             | no errors         |
      | Accident      | Caused By Debris On The Road                         | Third party vehicle damaged by debris from insured vehicle                                                       | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Owner   | no errors         |
      | Accident      | Caused By Debris On The Road                         | Debris from known third party                                                                                    | Insured Vehicle, Third Party Vehicle | Insured Driver, TP Driver  | no errors         |
      | Accident      | Caused By Debris On The Road                         | Debris from unknown third party                                                                                  | Insured Vehicle                      | Insured Driver             | no errors         |
      | Accident      | Changing Lanes                                       | Insured failed to notice third party vehicle                                                                     |                                      |                            |                   |
      | Accident      | Changing Lanes                                       | Swerved to avoid a vehicle which did not stop and collided with a third party                                    |                                      |                            |                   |
      | Accident      | Changing Lanes                                       | Swerved to avoid a vehicle which braked suddenly and collided with third party                                   |                                      |                            |                   |
      | Accident      | Changing Lanes                                       | Third party failed to notice Insured                                                                             |                                      |                            |                   |
      | Accident      | Changing Lanes                                       | Third party swerved into my path                                                                                 |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Having swerved to avoid an animal which ran across the road                                                      |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Having swerved to avoid a pedestrian crossing the road                                                           |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Having had attention distracted                                                                                  |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Basic error of judgement                                                                                         |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Having lost concentration due to fatigue                                                                         |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Lost control due to mechanical failure                                                                           |                                      |                            |                   |
      | Accident      | Collided With Fixed Object                           | Lost control due to black ice - adverse weather conditions                                                       |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Having had attention distracted                                                                                  |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Having lost concentration due to fatigue                                                                         |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Basic error of judgement                                                                                         |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Lost control due to mechanical failure                                                                           |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Lost control due to black ice - adverse weather conditions                                                       |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Having swerved to avoid an animal which ran across the road                                                      |                                      |                            |                   |
      | Accident      | Collided With Parked Third Party Vehicle at Roadside | Having swerved to avoid a pedestrian crossing the road                                                           |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Entering roundabout collided with third party vehicle from right                                                 |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Hit in rear by third party vehicle whilst waiting to enter roundabout                                            |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Hit in rear by third party vehicle whilst negotiating roundabout                                                 |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Collided with nearside of third party vehicle whilst negotiating a roundabout                                    |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Collided with offside of third party vehicle when attempting to leave roundabout                                 |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Hit rear of third party vehicle whilst negotiating roundabout                                                    |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Hit rear of third party vehicle who was waiting to enter roundabout                                              |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Negotiating roundabout - when third party vehicle entered from left                                              |                                      |                            |                   |
      | Accident      | Collision At Roundabout                              | Third party vehicle changed lanes without warning                                                                |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured emerged from minor road into path of third party TP gave misleading signal                               |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured emerged from minor road into path of third party                                                         |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Third party vehicle emerged from minor road into path of insured who was overtaking a line of stationary traffic |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured turned left as third party vehicle attempted to pass on nearside                                         |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured turned right across path of oncoming third party vehicle                                                 |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured turned right as third party vehicle attempted to pass on offside                                         |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Third party vehicle emerged from minor road into path of insured                                                 |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Insured turning right out of minor road - into path of TP overtaking a line of stationary traffic                |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Third party turned right as insured attempted to pass on offside                                                 |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Third party turned left as insured attempted to pass on nearside                                                 |                                      |                            |                   |
      | Accident      | Collision At 'T' Junction                            | Oncoming third party vehicle turned right across path of insured                                                 |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by 'give way' signs - Insured on major road                                                             |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by 'give way' signs - Insured on minor road                                                             |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Insured turned right across path of oncoming third party vehicle - no filter light                               |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Insured turning left hit by third party                                                                          |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Insured turning right across path of third party                                                                 |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Neither party had right of way                                                                                   |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by 'stop' signs - Insured on major road                                                                 |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by 'stop' signs - Insured on minor road                                                                 |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Oncoming third party vehicle turned right across path of insured - no filter light                               |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Third party turning left (no signal) hit by Insured                                                              |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Third party turning left (having signalled correctly) hit by Insured                                             |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Third party turning right (no signal) across path of Insured                                                     |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Third party turning right (having signalled correctly) across path of insured                                    |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by traffic lights - Insured crossed on amber                                                            |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by traffic lights - Insured crossed on green                                                            |                                      |                            |                   |
      | Accident      | Collision At 'X' Roads                               | Governed by traffic lights - Insured crossed on red                                                              |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Three lane carriage way - no priorities                                                                          |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Three lane carriage way - priority with insured                                                                  |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Three lane carriage way - priority with third party                                                              |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Insured entered 'one way' street the wrong way and collided with oncoming third party vehicle                    |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Insured turned right across path of oncoming third party vehicle                                                 |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Insured lost control and collided with oncoming third party vehicle                                              |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | In narrow lane - neither party had right of way                                                                  |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | On bend in narrow lane - neither party had right of way                                                          |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Oncoming third party vehicle lost control and collided with insured                                              |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Insured vehicle overtaking on wrong side of road collided with oncoming third party vehicle                      |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Collided with oncoming vehicle in a road reduced in width by parked cars on both sides                           |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Passing parked vehicle(s) in collision with oncoming third party                                                 |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Collided with an oncoming third party who was passing parked vehicle(s)                                          |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Having swerved to avoid a pedestrian                                                                             |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Oncoming third party vehicle entered 'one way' street the wrong way and collided with Insured                    |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Oncoming third party vehicle overtaking on wrong side of road collided with insured                              |                                      |                            |                   |
      | Accident      | Collision Between Oncoming Vehicles                  | Oncoming third party vehicle turned right across path of insured                                                 |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Both parties reversing                                                                                           |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Having swerved to avoid a pedestrian                                                                             |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Having had attention distracted                                                                                  |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Lost control due to mechanical failure                                                                           |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Having swerved to avoid another vehicle which did not stop                                                       |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Lost control due to black ice - adverse weather conditions                                                       |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Basic error of judgement                                                                                         |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Insured reversed into third party vehicle                                                                        |                                      |                            |                   |
      | Accident      | Collision In Car Park                                | Third party reversed into insured vehicle in a car park                                                          |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Both parties reversing                                                                                           |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | collided with bollard                                                                                            |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Lost control due to black ice - adverse weather conditions                                                       |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Lost control due to mechanical failure                                                                           |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Collided with moving third party vehicle                                                                         |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Other innate object                                                                                              |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Collided with parked third party vehicle                                                                         |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Struck pedestrian/child                                                                                          |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Collided with post/pillar/wall                                                                                   |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Insured reversed into third party vehicle                                                                        |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Third party reversed into insured vehicle                                                                        |                                      |                            |                   |
      | Accident      | Collision Whilst Reversing                           | Third party was reversing and colliding with our correctly proceeding vehicle                                    |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Whilst waiting to enter main road at 'T' junction                                                                |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Hit in rear and pushed into passing vehicle                                                                      |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Hit in rear and pushed into vehicle in front                                                                     |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Hit In Rear while correctly proceeding along the road                                                            |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Whilst slowing down for an animal crossing the road                                                              |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Whilst slowing down for people crossing the road                                                                 |                                      |                            |                   |
      | Accident      | Hit in Rear By Third Party                           | Whilst stationary at 'X' roads                                                                                   |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle stationary at 'X' roads                                                                      |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle while correctly proceeding along the road                                                    |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle whilst in line of slow moving traffic                                                        |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle stationary in line of traffic                                                                |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle and pushed into passing vehicle                                                              |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle turning off main road                                                                        |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle negotiating roundabout                                                                       |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle slowing down for an animal crossing the road                                                 |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle whilst slowing down for people crossing the road                                             |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle waiting to enter main road at 'T' junction                                                   |                                      |                            |                   |
      | Accident      | Hit Rear Of Third Party                              | Hit rear of vehicle waiting to enter roundabout                                                                  |                                      |                            |                   |
      | Accident      | Insured Vehicle Damaged Whilst Parked                | In private car park                                                                                              |                                      |                            |                   |
      | Accident      | Insured Vehicle Damaged Whilst Parked                | In public car park                                                                                               |                                      |                            |                   |
      | Accident      | Insured Vehicle Damaged Whilst Parked                | On road not outside own home                                                                                     |                                      |                            |                   |
      | Accident      | Insured Vehicle Damaged Whilst Parked                | On road outside own home                                                                                         |                                      |                            |                   |
      | Accident      | Insured Vehicle Damaged Whilst Parked                | In works car park                                                                                                |                                      |                            |                   |
      | Accident      | Insured's Vehicle Left Road                          | Obstruction / debris in the road                                                                                 |                                      |                            |                   |
      | Accident      | Insured's Vehicle Left Road                          | Poor road / weather conditions                                                                                   |                                      |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Insured failed to notice third party vehicle on main road                                                        | Fault                                |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Insured failed to give way to traffic on main road                                                               | Fault                                |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Insured took wrong exit - collision with third party                                                             | Fault                                |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Third party failed to give way to traffic on main road                                                           | Non Fault                            |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Third party failed to notice insured vehicle on main road                                                        | Fault                                |                            |                   |
      | Accident      | Joining/Leaving Slip Roads/Motorways                 | Insured collided with third party who had taken wrong exit                                                       | Non Fault                            |                            |                   |
      | Accident      | Loss of Consciousness / Automatism                   | Caused by known condition - own damage only                                                                      | Fault                                |                            |                   |
      | Accident      | Loss of Consciousness / Automatism                   | Caused by unknown condition - own damage only                                                                    | Non Fault                            |                            |                   |
      | Accident      | Loss of Consciousness / Automatism                   | Caused by known condition - involving TP vehicle / property                                                      | Fault                                |                            |                   |
      | Accident      | Loss of Consciousness / Automatism                   | Caused by unknown condition - involving TP vehicle / property                                                    | Non Fault                            |                            |                   |
      | Accident      | Loss Of Control                                      | Insured failed to negotiate left hand bend                                                                       | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Insured lost control due to adverse weather conditions                                                           | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Lost Control Human Error                                                                                         | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Lost control due to mechanical failure                                                                           | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Having had attention distracted                                                                                  | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Insured failed to negotiate right hand bend                                                                      | Fault                                |                            |                   |
      | Accident      | Loss Of Control                                      | Turning corner into/out of side road - mounted pavement                                                          | Fault                                |                            |                   |
      | Accident      | Moving From Stationary Position                      | Insured into path of third party who gave a misleading signal                                                    | Split Liability                      |                            |                   |
      | Accident      | Moving From Stationary Position                      | Insured out of lay-by into path of third party who gave a misleading signal                                      | Split Liability                      |                            |                   |
      | Accident      | Moving From Stationary Position                      | Insured attempting 'U' turn, collision with third party                                                          | Fault                                |                            |                   |
      | Accident      | Moving From Stationary Position                      | Insured into path of third party                                                                                 | Fault                                |                            |                   |
      | Accident      | Moving From Stationary Position                      | Insured out of lay-by into path of third party                                                                   | Fault                                |                            |                   |
      | Accident      | Moving From Stationary Position                      | Third party into path of Insured who gave a misleading signal                                                    | Split Liability                      |                            |                   |
      | Accident      | Moving From Stationary Position                      | Third party into path of insured                                                                                 | Non Fault                            |                            |                   |
      | Accident      | Moving From Stationary Position                      | Third Party out of lay-by into path of insured                                                                   | Non Fault                            |                            |                   |
      | Accident      | Moving From Stationary Position                      | Third party out of lay-by into path of insured who gave a misleading signal                                      | Split Liability                      |                            |                   |
      | Accident      | Moving From Stationary Position                      | Third party attempted 'U' turn, collision with insured                                                           | Non Fault                            |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Third party from side road - multiple collision on main                                                          | Non Fault                            |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Motorway multiple vehicles                                                                                       | Fault                                |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Insured hit rear of TP forcing it into rear of another                                                           | Fault                                |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Insured struck rear of TP before being hit from behind                                                           | Fault                                |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Insured shunted from rear into TP in front                                                                       | Non Fault                            |                            |                   |
      | Accident      | Multiple Vehicle - Shunt                             | Insured from side road - multiple collision on main                                                              | Fault                                |                            |                   |
      | Accident      | Narrow Road Collision                                | Brow of a hill / bridge                                                                                          | Split Liability                      |                            |                   |
      | Accident      | Narrow Road Collision                                | Narrow road / country Lane                                                                                       | Split Liability                      |                            |                   |
      | Accident      | Narrow Road Collision                                | Insured passing parked cars                                                                                      | Fault                                |                            |                   |
      | Accident      | Narrow Road Collision                                | Road narrowed by parked cars either side                                                                         | Split Liability                      |                            |                   |
      | Accident      | Narrow Road Collision                                | Insured rounding bend                                                                                            | Split Liability                      |                            |                   |
      | Accident      | Narrow Road Collision                                | Third party rounding bend                                                                                        | Split Liability                      |                            |                   |
      | Accident      | Narrow Road Collision                                | Third party passing parked cars                                                                                  | Non Fault                            |                            |                   |
      | Accident      | Overtaking                                           | Insured from behind hit off side of third party vehicle                                                          | Fault                                |                            |                   |
      | Accident      | Overtaking                                           | Insured hit oncoming third party                                                                                 | Fault                                |                            |                   |
      | Accident      | Overtaking                                           | Third Party from behind hit off side of vehicle                                                                  | Non Fault                            |                            |                   |
      | Accident      | Overtaking                                           | Third Party hit oncoming Insured                                                                                 | Non Fault                            |                            |                   |
      | Accident      | Reported by TP                                       | Reported by TP                                                                                                   | Fault                                |                            |                   |
      | Accident      | Unknown                                              | Unknown                                                                                                          | Fault                                |                            |                   |

  @Ignore
  Scenario: CBPCL-200 TC2 Fire Incident type, cause and subcauses will cause correct validation at end of step3
    When I add "<incidents added>" to the claim
    And I add "<parties added>" to the claim
    And I select "Next"
    Then I will see the validation errors "<validation errors>"
      | incident type | cause                   | sub cause                                                              | incidents added                      | parties added              | validation errors         |
      | Fire          | Vehicle Damaged By Fire | Arson attack                                                           | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Arson attack                                                           |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Dropped cigarette/match/lighter                                        | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Dropped cigarette/match/lighter                                        |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Garage fire                                                            | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Garage fire                                                            |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Manufacturer defect                                                    | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Manufacturer defect                                                    |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing DIY mechanical repair                                | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing DIY mechanical repair                                |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing mechanical repair by third party                     | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing mechanical repair by third party                     |                                      | Missing Insured Vehicle    |                           |
      | Fire          | Vehicle Damaged By Fire | Petrol leakage (whilst idling)                                         | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Petrol leakage (whilst idling)                                         |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Petrol leakage (whilst travelling)                                     | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Petrol leakage (whilst travelling)                                     |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a property on fire                          | Insured Vehicle                      | Third Party Property Owner | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a property on fire                          |                                      | Third Party Property Owner | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a property on fire                          | Insured Vehicle                      |                            | Missing TP Property Owner |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a vehicle on fire                           | Insured Vehicle, Third Party Vehicle | Third Party Vehicle Owner  | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a vehicle on fire                           | Third Party Vehicle                  | Third Party Vehicle Owner  | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a vehicle on fire                           | Insured Vehicle                      | Third Party Vehicle Owner  | Missing TP Vehicle        |
      | Fire          | Vehicle Damaged By Fire | Parked next to or close by a vehicle on fire                           | Insured Vehicle, Third Party Vehicle |                            | Missing TP Vehicle Owner  |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing DIY structural repair, including welding             | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing DIY structural repair, including welding             |                                      |                            | Missing Insured Vehicle   |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing structural repair, including welding, by third party | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Whilst undergoing structural repair, including welding, by third party |                                      | Missing Insured Vehicle    |                           |
      | Fire          | Vehicle Damaged By Fire | Wiring fault                                                           | Insured Vehicle                      |                            | no errors                 |
      | Fire          | Vehicle Damaged By Fire | Wiring fault                                                           |                                      |                            | Missing Insured Vehicle   |

  @Ignore
  Scenario: CBPCL-200 TC3 Flood/Water Damage Incident type, cause and subcauses will cause correct validation at end of step3
    When I add "<incidents added>" to the claim
    And I add "<parties added>" to the claim
    And I select "Next"
    Then I will see the validation errors "<validation errors>"
      | incident type      | cause                | sub cause                                             | incidents added | parties added | validation errors |
      | Flood/Water Damage | Flood / Water Damage | Attempted to drive through Flooded area - fresh water |                 |               |                   |
      | Flood/Water Damage | Flood / Water Damage | Attempted to drive through Flooded area - sea water   |                 |               |                   |
      | Flood/Water Damage | Flood / Water Damage | Vehicle immersed in fresh water                       |                 |               |                   |
      | Flood/Water Damage | Flood / Water Damage | Vehicle immersed in sea water                         |                 |               |                   |

  Scenario: CBPCL-200  TC8  Theft Incident type, cause and subcauses will cause correct validation at end of step3
    And the "<incidents added>" vehicle is selected
    And I move to step3 of FNOL
    When I add "<incidents added>" to the claim
    And I add "<parties added>" to the claim
    And I select "Next"
    Then I will see the validation errors "<validation errors>"
      | incident type | cause              | sub cause                                               | incidents added | parties added | validation errors       |
      | Theft         | Theft From Vehicle | Audio from locked vehicle                               | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Audio from locked vehicle                               |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Audio from unlocked vehicle                             | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Audio from unlocked vehicle                             |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Stolen by force / threat of violence / deception        | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Stolen by force / threat of violence / deception        |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Personal items from locked vehicle                      | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Personal items from locked vehicle                      |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Personal items from unlocked vehicle                    | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Personal items from unlocked vehicle                    |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Bodywork parts stolen from locked vehicle               | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Bodywork parts stolen from locked vehicle               |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Satellite Navigation stolen from locked vehicle         | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Satellite Navigation stolen from locked vehicle         |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Satellite Navigation stolen from unlocked vehicle       | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Satellite Navigation stolen from unlocked vehicle       |                 |               | Missing Insured Vehicle |
      | Theft         | Theft From Vehicle | Theft Of wheels                                         | Insured Vehicle |               | no errors               |
      | Theft         | Theft From Vehicle | Theft Of wheels                                         |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | Stolen by force / threat of violence / deception        | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | Stolen by force / threat of violence / deception        |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | Stolen whilst parked on the road - outside own home     | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | Stolen whilst parked on the road - outside own home     |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | Stolen whilst parked on the road - not outside own home | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | Stolen whilst parked on the road - not outside own home |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | From driveway - no locked gates                         | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | From driveway - no locked gates                         |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | From driveway - secured by locked gates                 | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | From driveway - secured by locked gates                 |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | From locked garage                                      | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | From locked garage                                      |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Unrecovered  | From unlocked garage                                    | Insured Vehicle |               | no errors               |
      | Theft         | Theft Unrecovered  | From unlocked garage                                    |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | Stolen by force / threat of violence / deception        | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | Stolen by force / threat of violence / deception        |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | Stolen whilst parked on the road - outside own home     | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | Stolen whilst parked on the road - outside own home     |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | Stolen whilst parked on the road - not outside own home | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | Stolen whilst parked on the road - not outside own home |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | From driveway - no locked gates                         | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | From driveway - no locked gates                         |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | From driveway - secured by locked gates                 | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | From driveway - secured by locked gates                 |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | From locked garage                                      | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | From locked garage                                      |                 |               | Missing Insured Vehicle |
      | Theft         | Theft Recovered    | From unlocked garage                                    | Insured Vehicle |               | no errors               |
      | Theft         | Theft Recovered    | From unlocked garage                                    |                 |               | Missing Insured Vehicle |
      | Theft         | Attempted Theft    | Boot damaged / forced open                              | Insured Vehicle |               | no errors               |
      | Theft         | Attempted Theft    | Boot damaged / forced open                              |                 |               | Missing Insured Vehicle |
      | Theft         | Attempted Theft    | Door forced/lock drilled out/lock forced                | Insured Vehicle |               | no errors               |
      | Theft         | Attempted Theft    | Door forced/lock drilled out/lock forced                |                 |               | Missing Insured Vehicle |
      | Theft         | Attempted Theft    | Rear window broken in an attempt to gain entry          | Insured Vehicle |               | no errors               |
      | Theft         | Attempted Theft    | Rear window broken in an attempt to gain entry          |                 |               | Missing Insured Vehicle |
      | Theft         | Attempted Theft    | Side window broken in an attempt to gain entry          | Insured Vehicle |               | no errors               |
      | Theft         | Attempted Theft    | Side window broken in an attempt to gain entry          |                 |               | Missing Insured Vehicle |
      | Theft         | Attempted Theft    | Steering lock damaged/forced                            | Insured Vehicle |               | no errors               |
      | Theft         | Attempted Theft    | Steering lock damaged/forced                            |                 |               | Missing Insured Vehicle |
